apiVersion: batch/v1
kind: CronJob
metadata:
  name: app-test-cronjob
  labels: app-test
spec:
  schedule: "0 0 1 1 *"
  concurrencyPolicy: Allow
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        spec:
          volumes:
            - name: config-volume
              configMap:
                name: app-volume1
          containers:
            - name: app-test-cron
              image: public.ecr.aws/ubuntu/ubuntu:24.04_stable
              command: ["/bin/sh", "sh cp /tmp/config/lastlog /var/log/ && sh /tmp/test-script.sh" ]
              volumeMounts:
                - name: config-volume
                  mountPath: "/tmp/config/lastlog"
                  subPath: lastlog
                - name: config-volume
                  mountPath: "/tmp/config/lastlog-2"
                  subPath: lastlog-2
                - name: config-volume
                  mountPath: "/tmp/test-script.sh"
                  subPath: test-script.sh
          restartPolicy: OnFailure
