apiVersion: apps/v1
kind: CronJob
metadata:
  name: app-test
  labels: app-test
spec:
  schedule: 0 0 1 1 *
  revisionHistoryLimit: 3
  concurrencyPolicy: Allow
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      containers:
      - image: public.ecr.aws/ubuntu/ubuntu:24.04_stable
        name: app-test
        command: ["/bin/sh", "-c", "sleep 3000" ]
        args: ["/bin/sh", "-c", "cp /tmp/config/* /var/log/ && sh /tmp/test-script.sh"]
        volumeMounts:
        - name: config-volume
          mountPath: "/tmp/config/lastlog"
          subPath: lastlog
        - name: config-volume
          mountPath: "/tmp/config/lastlog-2"
          subPath: lastlog-2
        - name: config-volume
          mountPath: "/tmp/test-script.sh"
          subPath: test-script.sh
      volumes:
      - name: config-volume
        configMap:
          name: app-volume1
