apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-test
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: app-test
  template:
    metadata:
      labels:
        app: app-test
    spec:
      containers:
      - image: public.ecr.aws/ubuntu/ubuntu:24.04_stable
        name: app-test
        command: ["/bin/sh", "-c", "sleep 3000" ]
        volumeMounts:
        - name: config-volume
          mountPath: "/tmp/config/lastlog"
          subPath: lastlog
        - name: config-volume
          mountPath: "/tmp/config/lastlog-2"
          subPath: lastlog-2
      volumes:
      - name: config-volume
        configMap:
          name: app-volume1
